import Universals.Correspondences.Predicates.Unary.Functional
import Universals.Correspondences.Predicates.Unary.Injective
import Universals.Correspondences.Predicates.Unary.Total
import Universals.Correspondences.Predicates.Unary.Surjective
