import Universals.Correspondences.Operations.Unary.Application
import Universals.Correspondences.Operations.Unary.Domain
import Universals.Correspondences.Operations.Unary.Range
import Universals.Correspondences.Operations.Unary.CoClassification
