import Logic.PredicateCalculus.Schemas.CongruentPredicates.Binary.Instances.Equals.Properties.LeftTotality
import Logic.PredicateCalculus.Schemas.CongruentPredicates.Binary.Instances.Equals.Properties.RightDeterminacy
