name = "lean-math"
version = "0.1.0"
defaultTargets = ["lean-math"]

 [[lean_lib]]
 name = "LeanMath"

[[lean_lib]]
name = "Logic"

[[lean_lib]]
name = "Universals"

[[lean_lib]]
name = "Universe"

[[lean_lib]]
name = "Core"

[[lean_exe]]
name = "lean-math"
root = "Main"
