import Universals.Sets.Universals.Singleton.Predicates.Binary.SingletonElemGraph.Properties.LeftTotality
import Universals.Sets.Universals.Singleton.Predicates.Binary.SingletonElemGraph.Properties.RightDeterminacy
