import Logic.PredicateCalculus.Schemas.CongruentPredicates.Unary.Instances.True
import Logic.PredicateCalculus.Schemas.CongruentPredicates.Unary.Instances.False
import Logic.PredicateCalculus.Schemas.CongruentPredicates.Unary.Instances.Equals
