import Logic.PredicateCalculus.Schemas.CongruentPredicates.Unary.Properties.NegationPreservesCongruence
import Logic.PredicateCalculus.Schemas.CongruentPredicates.Unary.Properties.ConjunctionPreservesCongruence
import Logic.PredicateCalculus.Schemas.CongruentPredicates.Unary.Properties.DisjunctionPreservesCongruence
import Logic.PredicateCalculus.Schemas.CongruentPredicates.Unary.Properties.ExistentialPreservesCongruence
import Logic.PredicateCalculus.Schemas.CongruentPredicates.Unary.Properties.UniversalPreservesCongruence
import Logic.PredicateCalculus.Schemas.CongruentPredicates.Unary.Properties.ExistsUniquePreservesCongruence
import Logic.PredicateCalculus.Schemas.CongruentPredicates.Unary.Properties.PropositionalEquivalencePreservesCongruence
