import Logic.PredicateCalculus.Schemas.CongruentPredicates.Unary.Properties.NegationPreservesCongruence
import Logic.PredicateCalculus.Schemas.CongruentPredicates.Unary.Properties.ConjunctionPreservesCongruence
