import Universals.Relations.Predicates.Unary.Reflexive.Predicate
import Universals.Relations.Predicates.Unary.Symmetric.Predicate
import Universals.Relations.Predicates.Unary.Transitive.Predicate
import Universals.Relations.Predicates.Unary.EquivalenceRelation.Predicate
import Universals.Relations.Predicates.Unary.PartialEquivalenceRelation.Predicate
import Universals.Relations.Predicates.Unary.QuasiReflexiveRelation.Predicate
