import Logic.PredicateCalculus.Definitions.StatementTemplate
import Logic.PredicateCalculus.Definitions.ExistsUnique
import Logic.PredicateCalculus.Definitions.Operations
import Logic.PredicateCalculus.Definitions.Predicates
