import Universals.Sets.Universals.Singleton.Predicates.Binary.Definitions.SingletonElemGraphPredicate
import Universals.Sets.Universals.Singleton.Predicates.Binary.Definitions.SingletonOfGraphPredicate
