import Universe

import Logic

import Universals.Sets.Particular

/-!
# Sets as Unary Predicates
A `Unary Predicate` introduces structure into the `Universe`, it partitions the `Particulars` into two, according to whether they satisfy the `Predicate` or not.
We call `Sets` these partitions.

A specific important case of partitions are those generated by the `Unary Predicates` P(x) = True and P(x) = False, which
partition the `Universe` into a `Set` that contains all `Particulars` in the `Universe`, i.e. the `Universal Set`,
and a `Set` that contains no `Particulars`, i.e. the `Empty Set`.

We can now define operations on `Sets` based on well-known `Predicate` operations and show that they are well-defined
and match the traditional set-theoretic operations.

The result is that we derived *Set Theory* from *Logic* (expressed through *Type Theory* via the Curry-Howard
isomorphism), by defining the meaning of `Set` membership in terms of `Predicate` satisfaction,
as opposed to introducing it as primitive notion, requiring axioms to define its behavior, like ZFC does.
All traditional `Set` operations and properties emerge from logical primitives: the existence of the `Empty Set` is derived
from falsehood, `Set` equality by extensionality from `Predicate` equality (two `Predicates` are equal if they are logically
equivalent), the `Powerset` is simply a predicate over predicates (`Sets` of `Sets`) requiring no additional axiom, and
crucially, we do not need the *Axiom of Infinity* because we show that the `Universe` is a `Set` whether it's finite
or infinite. Thus, three of ZFC's fundamental axioms (Empty Set, Powerset, and Infinity) are unnecessary—they are
either derived or rendered superfluous by our logical foundation.

Notice also that, while **Russell's Paradox** can still be expressed in the framework, by using an inconsistent `Recursive Predicate Definition`,
e.g. `P(x) := x ∉ P` (we already addressed this in `NaturalDeduction.md` Note 3), its realization via self-containment is prevented by the way
we define `Sets`, which creates an "stratification" that establishes an infinite hierarchy of `Particulars` we can reason about:

**Note on Terminology**: At each level, the entities being reasoned about are called `Particulars` relative to
that level's discourse. When we construct `Sets` at one level and then reason about those `Sets` at the next level,
those `Sets` become the `Particulars` of the higher-level discourse.

- *`Level 0 Particulars`*: the initial, i.e. base, `Particulars` we want to reason about.

- *`Level 1 Particulars`* (`Sets` of `Level 0 Particulars`): groupings of `Level 0 Particulars` according to their properties.
  A *Level 1 Particular* is a `Set` which contains only `Level 0 Particulars`, never other `Level 1 Particulars`.

- *`Level 2 Particulars`* (`Sets` of `Sets` of `Level 0 Particulars`): groupings of `Level 1 Particulars` according to their
properties.  A *Level 2 Particular* contains only `Level 1 Particulars`, i.e. `Sets` of `Level 0 Particulars`, never `Level 2 Particulars`.

- **Level 3 and beyond**: Each level groups `Particulars` from the immediately preceding level, according to their properties,
continuing indefinitely.

**Why This Prevents Russell's Paradox**: Russell's "set of all sets not containing themselves" requires a `Set`
to exist at the same level as its potential elements. But the hierarchy ensures `Sets` always exist one level
above their elements, making self-membership impossible at every level.

**Why This embeds (Finite) Higher-Order Logic Into First Order Logic**

A profound consequence of this framework is that it embeds higher-order logic within first-order logic, not by
adding new quantification rules, but as a natural consequence of defining `Sets` as `Predicates`.

Since `Sets`, i.e. `Set X`, are defined as a type whose terms are `Predicates` over `X`, first-order quantification over `Set X`
(e.g., `∀ S : Set X, ...`) syntactically uses first order typed quantification while semantically capturing predicate
quantification — achieving second-order logic within first-order syntax.

Similarly, `Sets`of `Sets`, i.e. `Set (Set X)`, are defined as a type whose terms are `Predicates` over `Sets`, i.e.
`Predicates` over `Predicates` over `X`, making first-order quantification over it semantically third-order, continuing
this pattern for all finite orders.

- **Key Distinction from Traditional Approaches**: Traditional higher-order logics introduce new syntactic machinery
(quantifiers over predicates, functions, etc.) as primitive extensions to first-order logic. Our framework shows
this is unnecessary: higher-order reasoning emerges *inevitably* from first-order logic once we:
  1. Define `Sets` as the extension of `Predicates`.
  2. Allow `Sets` themselves to become `Particulars` at the next level.

The stratification hierarchy is not an artificial restriction—it is the natural structure through which first-order
logic, given the right notion of predicate, generates all finite orders of higher-order logic internally.

**Why the Universe Set Exists**: The `Universal Set` is a `Level 1 Particular` defined by the `Predicate`
"being a `Level 0 Particular`". It contains all `Level 0 Particulars` but is itself a `Level 1 Particular`,
distinct from what it contains. There is no "set of all sets at all levels" because each level's totality
can only be described by the next level.


In the following: let `P₍a₎` denote the `Predicate` that gives place to the `Set` `A`.
-/

namespace Universe

open Logic
open Logic.PC₁


namespace Sets

-- # =ₛₑₜ is an equivalence relation

-- ## `Set` equality is reflexive
theorem eq_refl: ∀ (S: Sets.Particular U), S =ₛₑₜ S := by forall_intro
  variable(A: Sets.Particular U)
  have h₁: ∀ (S₂: Sets.Particular U), A =ₛₑₜ S₂ ↔ ∀ (x: U.Particular), A.pred x ↔ S₂.pred x := by forall_elim eq_def, A
  have h₂: A =ₛₑₜ A ↔ ∀ (x: U.Particular), A.pred x ↔ A.pred x := by forall_elim h₁, A
  have h₃: ∀ (x: U.Particular), A.pred x ↔ A.pred x := by forall_intro
    variable(a: U.Particular)
    have h₃₁: A.pred a → A.pred a := by
      assume(h₃₁₁: A.pred a)
      iterate h₃₁₁
    have h₃₂: A.pred a ↔ A.pred a := by iff_intro h₃₁, h₃₁
    iterate h₃₂
  have h₄: A =ₛₑₜ A := PC₀.deductive_eq_r2l h₂ h₃
  iterate h₄

-- ## `Set` equality is symmetric
theorem eq_sym: ∀ (S₁: Sets.Particular U), ∀ (S₂: Sets.Particular U), S₁ =ₛₑₜ S₂ → S₂ =ₛₑₜ S₁ := by forall_intro
  variable(A: Sets.Particular U)
  variable(B: Sets.Particular U)
  have h₁: ∀ S₂: Sets.Particular U, A =ₛₑₜ S₂ ↔ ∀ (x: U.Particular), A.pred x ↔ S₂.pred x := by forall_elim eq_def, A
  have h₂: A =ₛₑₜ B ↔ ∀ (x: U.Particular), A.pred x ↔ B.pred x := by forall_elim h₁, B
  have h₃: ∀ S₂: Sets.Particular U, B =ₛₑₜ S₂ ↔ ∀ (x: U.Particular), B.pred x ↔ S₂.pred x := by forall_elim eq_def, B
  have h₄: B =ₛₑₜ A ↔ ∀ (x: U.Particular), B.pred x ↔ A.pred x := by forall_elim h₃, A
  have h₅: A =ₛₑₜ B → B =ₛₑₜ A := by
    assume(h₅₁: A =ₛₑₜ B)
    have h₅₂: ∀ (x: U.Particular), B.pred x ↔ A.pred x := by forall_intro
      variable(a: U.Particular)
      have h₅₂₁: ∀ (x: U.Particular), A.pred x ↔ B.pred x := PC₀.deductive_eq_l2r h₂ h₅₁
      have h₅₂₂: A.pred a ↔ B.pred a := by forall_elim h₅₂₁, a
      have h₅₂₃: B.pred a ↔ A.pred a := PC₀.deductive_eq_l2r PC₀.iff_comm h₅₂₂
      iterate h₅₂₃
    have h₅₃: B =ₛₑₜ A := PC₀.deductive_eq_r2l h₄ h₅₂
    iterate h₅₃
  iterate h₅

-- ## `Set` equality is transitive
theorem eq_trans: ∀ (S₁: Sets.Particular U), ∀ (S₂: Sets.Particular U), ∀ (S₃: Sets.Particular U), S₁ =ₛₑₜ S₂ ∧ S₂ =ₛₑₜ S₃ → S₁ =ₛₑₜ S₃ := by forall_intro
  variable(A: Sets.Particular U)
  variable(B: Sets.Particular U)
  variable(C: Sets.Particular U)
  have h₁: ∀ S₂: Sets.Particular U, A =ₛₑₜ S₂ ↔ ∀ (x: U.Particular), A.pred x ↔ S₂.pred x := by forall_elim eq_def, A
  have h₂: A =ₛₑₜ B ↔ ∀ (x: U.Particular), A.pred x ↔ B.pred x := by forall_elim h₁, B
  have h₃: ∀ S₂: Sets.Particular U, B =ₛₑₜ S₂ ↔ ∀ (x: U.Particular), B.pred x ↔ S₂.pred x := by forall_elim eq_def, B
  have h₄: B =ₛₑₜ C ↔ ∀ (x: U.Particular), B.pred x ↔ C.pred x := by forall_elim h₃, C
  have h₅: A =ₛₑₜ C ↔ ∀ (x: U.Particular), A.pred x ↔ C.pred x := by forall_elim h₁, C
  assume(h₆: A =ₛₑₜ B ∧ B =ₛₑₜ C)
  have h₇: A =ₛₑₜ B := by and_elim h₆
  have h₈: B =ₛₑₜ C := by and_elim h₆
  have h₉: ∀ (x: U.Particular), A.pred x ↔ B.pred x := PC₀.deductive_eq_l2r h₂ h₇
  have h₁₀: ∀ (x: U.Particular), B.pred x ↔ C.pred x := PC₀.deductive_eq_l2r h₄ h₈
  have h₁₁: ∀ (x: U.Particular), A.pred x ↔ C.pred x := by forall_intro
    variable(a: U.Particular)
    have h₁₁₁: A.pred a ↔ B.pred a := by forall_elim h₉, a
    have h₁₁₂: B.pred a ↔ C.pred a := by forall_elim h₁₀, a
    have h₁₁₃: A.pred a → C.pred a := by forall_intro
      assume(h₁₁₃₁: A.pred a)
      have h₁₁₃₂: B.pred a := PC₀.deductive_eq_l2r h₁₁₁ h₁₁₃₁
      have h₁₁₃₃: C.pred a := PC₀.deductive_eq_l2r h₁₁₂ h₁₁₃₂
      iterate h₁₁₃₃
    have h₁₁₄: C.pred a → A.pred a := by forall_intro
      assume(h₁₁₄₁: C.pred a)
      have h₁₁₄₂: B.pred a := PC₀.deductive_eq_r2l h₁₁₂ h₁₁₄₁
      have h₁₁₄₃: A.pred a := PC₀.deductive_eq_r2l h₁₁₁ h₁₁₄₂
      iterate h₁₁₄₃
    have h₁₁₃: A.pred a ↔ C.pred a := by iff_intro h₁₁₃, h₁₁₄
    iterate h₁₁₃
  have h₁₂: A =ₛₑₜ C := PC₀.deductive_eq_r2l h₅ h₁₁
  iterate h₁₂

-- # `Set` equality
def equality: Equality (Sets.Particular U) :=
  let pred: Sets.Particular U → Sets.Particular U → Prop := eq
  let refl: ∀ (x: Sets.Particular U), pred x x := eq_refl
  let sym: ∀ (x: Sets.Particular U), ∀ (y: Sets.Particular U), pred x y → pred y x := eq_sym
  let trans: ∀ (x: Sets.Particular U), ∀ (y: Sets.Particular U), ∀  (z: Sets.Particular U), pred x y ∧ pred y z → pred x z := eq_trans
  { pred:= pred, refl:= refl, sym:= sym, trans:= trans }

-- # `Set` Universal
def SetsUniversal (U: Universal): Universal := {
  Particular := Sets.Particular U
  eq:= equality
}
notation "𝐒𝐞𝐭" => SetsUniversal
abbrev Set U := (SetsUniversal U).Particular


end Sets

end Universe
