import Universals.Sets.Universals.Singleton.Predicates.Binary.SingletonOfGraph.Properties.LeftTotality
import Universals.Sets.Universals.Singleton.Predicates.Binary.SingletonOfGraph.Properties.RightDeterminacy
