import Logic.PredicateCalculus.Schemas.CongruentPredicates.Unary
import Logic.PredicateCalculus.Schemas.CongruentPredicates.Binary.Schema
import Logic.PredicateCalculus.Schemas.CongruentPredicates.Binary.Instances
