import Logic.PredicateCalculus.Schemas.CongruentPredicates.Binary
import Logic.PredicateCalculus.Schemas.CongruentPredicates.Ternary.Schema
import Logic.PredicateCalculus.Schemas.CongruentPredicates.Ternary.Properties
import Logic.PredicateCalculus.Schemas.CongruentPredicates.Ternary.Instances
